# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrantlyzer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='max_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
